model:
  type: diffusion # dsm and diffusion
  network: dualenc
  hidden_dim: 128
  num_convs: 6
  num_convs_local: 4
  cutoff: 10.0
  mlp_act: ReLU
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 9.e-3
  num_diffusion_timesteps: 5000
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: true

train:
  seed: 2021
  batch_size: 1
  val_freq: 100
  log_freq: 10
  max_iters: 3000000
  max_grad_norm: 30000.0  # Different from QM9
  anneal_power: 2.0
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    min_lr: 1.e-4
    factor: 0.6
    patience: 10

dataset:
  train: ./data/GEOM/Drugs/debug_1.pkl
  val: ./data/GEOM/Drugs/debug_1.pkl
  test: ./data/GEOM/Drugs/debug_1.pkl
