# config file for load dataset
# train contains batch_size, num_workers

train:
  batch_size: 32
  num_workers: 4
  # num_workers: 1
  # lambda_train: 0 # 0.01
  # lambda_valid: 0 # 0.01
  lambda_x_train: 0 # NOTE: For debugging
  lambda_q_train: 1 # NOTE: For debugging
  lambda_x_valid: 0 # NOTE: For debugging
  lambda_q_valid: 1 # NOTE: For debugging
  clip_grad: 5  # float, null to disable
  progress_bar: False
  weight_decay: 1e-12
  optimizer: adamw
  seed: 1994
  lr: 0.0005
  epochs: 10000

  check_val_every_n_epoch: 30000
  sample_every_n_batch: 30000
  sample_every_n_valid: 30000

  projection: True  # True or False
  noise_type: manifold  # euclidean or manifold

dataset:
  name: Geodesic2DFT
  datadir: 'data'
  raw_datadir: 'data/raw/GeodesictoDFT'

debug:
  save_dir: './debug'

general:
  name: 'test_leftnet'
  # name: 'debug'
  use_wandb: True
  wandb: 'online'
  save_model: True
  gpus: 1
  strategy: ddp  # 'deepspeed'  # auto, ddp, fsdp, deepspeed,
  resume: # ckpt path
  test_only: # /home/ksh/MolDiff/NeuralOpt/neural_opt/pl_test/checkpoints/fourth/epoch=96.ckpt
  evaluate_all_checkpoints:

sampling:
  stochastic: True
  sde_dt: 0.05
  gode_iter: 50
  gode_ref_dt: 0.05
  gode_max_dt: 0.1
  time_margin: 0.05

model:
  name: equivariant  # condensed
  pred_type: node
  hidden_dim: 128
  hidden_channels: 128 # same with hidden_dim
  num_bond_type: 10
  num_atom_type: 4
  num_atom_feat: 8
  score_act: 'silu'
  edge_cat_act: 'silu'
  edge_encoder:
    name: 'mlp'
    activation: 'silu'
  graph_encoder:
    name: leftnet
    pos_require_grad: False
    cutoff: 10.0
    num_layers: 6
    hidden_channels: 128 # same with hidden_dim
    num_radial: 96
    in_hidden_channels: 165 #  num_atom_feat * 10 * 2 + num_atom_type + 1
    reflect_equiv: True
    legacy: True
    update: True
    pos_grad: False
    single_layer_output: True
    for_conf: False
    ff: False
    object_aware: False

diffusion:
  scheduler:
    name: 'bellcurve'
    sigma_min: 1e-07
    sigma_max: 0.001
    beta_std: 0.125

manifold:
  ode_solver:
    vpae_thresh: 0.03  # percent error threshold
    alpha: 1.6
    beta: 2.3
    svd_tol: 1e-6
    iter: 30
    max_iter: 1000
    ref_dt: 5e-2
    _ref_dt: 1e-3
    max_dt: 1e-1
    _max_dt: 5e-2
    min_dt: 1e-3
    _min_dt: 1e-4
    pos_adjust_scaler: 0.03
    pos_adjust_thresh: 3e-3
    q_type: morse
