# config file for load dataset
# train contains batch_size, num_workers

train:
  batch_size: 64
  # batch_size: 1
  num_workers: 1
  lambda_x_train: 0 # NOTE: For debugging
  lambda_q_train: 1 # NOTE: For debugging
  lambda_x_valid: 0 # NOTE: For debugging
  lambda_q_valid: 1 # NOTE: For debugging
  # lambda_x_train: 1 # NOTE: For debugging
  # lambda_q_train: 0 # NOTE: For debugging
  # lambda_x_valid: 1 # NOTE: For debugging
  # lambda_q_valid: 0 # NOTE: For debugging
  clip_grad: 0.5  # float, null to disable
  progress_bar: False
  weight_decay: 1e-12
  optimizer: adamw
  seed: 1994
  # lr: 0.001
  lr: 0.0005
  # lr: 0.002
  epochs: 10000

  check_val_every_n_epoch: 3
  # check_val_every_n_epoch: 30000
  sample_every_n_batch: 30000
  sample_every_n_valid: 30000
  # sample_every_n_batch: 1
  # sample_every_n_valid: 1 
  # sample_every_n_batch: 100
  # sample_every_n_valid: 100

  projection: True  # True or False
  noise_type: manifold  # euclidean or manifold
  # noise_type: straight_to_x0
  # noise_type: euclidean

dataset:
  name: Geodesic2DFT
  datadir: 'data'
  # raw_datadir: 'data/raw/GeodesictoDFT'
  raw_datadir: 'GeodesictoDFT'
  dtype: float32
  data_split: "/home/share/DATA/NeuralOpt/data/data_split.pkl"

debug:
  save_dir: './debug'
  save_dynamic:
  # save_dynamic: './save_dynamic.pt'

general:
  # name: '20240412_schnet_appendFalse'
  # name: '20240412_schnet_appendTrue'
  name: '20240418_schnet_appendTrue_manifold'
  # name: 'debug'
  use_wandb: True
  # use_wandb: False 
  wandb: 'online'
  save_model: True
  # gpus: 8
  gpus: 1
  strategy: ddp  # 'deepspeed'  # auto, ddp, fsdp, deepspeed,
  resume: # ckpt path
  test_only: #./checkpoints/20240327_euclidean/last.ckpt
  evaluate_all_checkpoints:

sampling:
  stochastic: True
  # sde_dt: 0.05
  sde_dt: 0.01
  gode_iter: 50
  gode_ref_dt: 0.05
  gode_max_dt: 0.1
  time_margin: 0.05

model:
  # append_coordinate: False  # True or False
  # reduced_dimension: False # True or False
  append_coordinate: True # True or False
  reduced_dimension: True # True or False
  name: condensed
  pred_type: edge  # edge or node
  hidden_dim: 128
  num_bond_type: 10
  num_atom_type: 4
  num_atom_feat: 8
  score_act: 'silu'
  edge_cat_act: 'silu'
  edge_encoder:
    name: 'mlp'
    activation: 'silu'
  graph_encoder:
    name: 'schnet'
    node_dim: 128
    time_dim: 256
    edge_dim: 128
    num_filters: 128
    num_convs: 8
    cutoff: 10.0
    smooth_conv: False

diffusion:
  scheduler:
    name: 'bellcurve'
    # sigma_min: 1e-07
    sigma_min: 2e-06
    sigma_max: 0.001
    # sigma_max: 0.01
    beta_std: 0.125

# Fast sampling
manifold:
  ode_solver:
    vpae_thresh: 1e+9  # percent error threshold
    alpha: 1.6
    beta: 2.3
    gamma: 0.0
    svd_tol: 1e-1
    iter: 1
    max_iter: 1
    ref_dt: 1e+9
    _ref_dt: 1e+9
    max_dt: 1e+9
    _max_dt: 1e+9
    min_dt: 1e-3
    _min_dt: 1e-4
    pos_adjust_scaler: 0.03
    pos_adjust_thresh: 3e-3
    q_type: morse
